//Database has already been populated with the book data
//The program is working out of the Database created, not the generation of seed data

using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace OnlineBookstore.Models
{
    public class SeedData
    {
        //Method for checking for migrations and adding data to empty database
        public static void EnsurePopulated(IApplicationBuilder application)
        {
            BookstoreDbContext context = application.ApplicationServices.CreateScope().ServiceProvider.
                GetRequiredService<BookstoreDbContext>();

            //Migrate if migrations are needed
            if (context.Database.GetPendingMigrations().Any())
            {
                context.Database.Migrate();
            }
            
            //If there are no books in the database, create new book instances to add
            if (!context.Books.Any())
            {
                context.Books.AddRange
                    (
                        new Book
                        {
                            //Because BookId was specified as a key, it will be autogenerated when the object is created
                            //BookId = 1,
                            Title = "Les Miserables",
                            AuthorFirstName = "Victor",
                            AuthorLastName = "Hugo",
                            Publisher = "Signet",
                            ISBN = "978-0451419439",
                            Classification = "Fiction",
                            Category = "Classic",
                            Price = 9.95,
                            PageCount = 1488
                        },
                        new Book
                        {
                            Title = "Team of Rivals",
                            AuthorFirstName = "Doris",
                            AuthorMiddleName = "Kearns",
                            AuthorLastName = "Goodwin",
                            Publisher = "Simon & Schuster",
                            ISBN = "978-0743270755",
                            Classification = "Non-Fiction",
                            Category = "Biography",
                            Price = 14.58,
                            PageCount = 944
                        },
                        new Book
                        {
                            Title = "The Snowball",
                            AuthorFirstName = "Alice",
                            AuthorLastName = "Schroeder",
                            Publisher = "Bantam",
                            ISBN = "978-0553384611",
                            Classification = "Non-Fiction",
                            Category = "Biography",
                            Price = 21.54,
                            PageCount = 832
                        },
                        new Book
                        {
                            Title = "American Ulysses",
                            AuthorFirstName = "Ronald",
                            AuthorMiddleName = "C.",
                            AuthorLastName = "White",
                            Publisher = "Random House",
                            ISBN = "978-0812981254",
                            Classification = "Non-Fiction",
                            Category = "Biography",
                            Price = 11.61,
                            PageCount = 864
                        },
                        new Book
                        {
                            Title = "Unbroken",
                            AuthorFirstName = "Laura",
                            AuthorLastName = "Hillenbrand",
                            Publisher = "Random House",
                            ISBN = "978-0812974492",
                            Classification = "Non-Fiction",
                            Category = "Historical",
                            Price = 13.33,
                            PageCount = 528
                        },
                        new Book
                        {
                            Title = "The Great Train Robbery",
                            AuthorFirstName = "Michael",
                            AuthorLastName = "Crichton",
                            Publisher = "Vintage",
                            ISBN = "978-0804171281",
                            Classification = "Fiction",
                            Category = "Historical Fiction",
                            Price = 15.95,
                            PageCount = 288
                        },
                        new Book
                        {
                            Title = "Deep Work",
                            AuthorFirstName = "Cal",
                            AuthorLastName = "Newport",
                            Publisher = "Grand Central Publishing",
                            ISBN = "978-1455586691",
                            Classification = "Non-Fiction",
                            Category = "Self-Help",
                            Price = 14.99,
                            PageCount = 304
                        },
                        new Book
                        {
                            Title = "It's Your Ship",
                            AuthorFirstName = "Michael",
                            AuthorLastName = "Abrashoff",
                            Publisher = "Grand Central Publishing",
                            ISBN = "978-1455523023",
                            Classification = "Non-Fiction",
                            Category = "Self-Help",
                            Price = 21.66,
                            PageCount = 240
                        },
                        new Book
                        {
                            Title = "The Virgin Way",
                            AuthorFirstName = "Richard",
                            AuthorLastName = "Branson",
                            Publisher = "Portfolio",
                            ISBN = "978-1591847984",
                            Classification = "Non-Fiction",
                            Category = "Business",
                            Price = 29.16,
                            PageCount = 400
                        },
                        new Book
                        {
                            Title = "Sycamore Row",
                            AuthorFirstName = "John",
                            AuthorLastName = "Grisham",
                            Publisher = "Bantam",
                            ISBN = "978-0553393613",
                            Classification = "Fiction",
                            Category = "Thriller",
                            Price = 15.03,
                            PageCount = 642 
                        },

                        //New Books added after implementing pagination
                        //Required rerunning migrations and updating the database
                        new Book
                        {
                            Title = "The Way of Kings",
                            AuthorFirstName = "Brandon",
                            AuthorLastName = "Sanderson",
                            Publisher = "Tor Fantasy",
                            ISBN = "978-0765365279",
                            Classification = "Fiction",
                            Category = "Fantasy",
                            Price = 9.59,
                            PageCount = 1280
                        },
                        new Book
                        {
                            Title = "All Systems Red",
                            AuthorFirstName = "Martha",
                            AuthorLastName = "Wells",
                            Publisher = "Tor",
                            ISBN = "978-0765397539",
                            Classification = "Science Fiction",
                            Category = "Fantasy",
                            Price = 13.39,
                            PageCount = 160
                        },
                        new Book
                        {
                            Title = "20,000 Leagues Under the Sea",
                            AuthorFirstName = "Jules",
                            AuthorLastName = "Verne",
                            Publisher = "Wordsworth Editions Ltd",
                            ISBN = "978-1853260315",
                            Classification = "Science Fiction",
                            Category = "Classic",
                            Price = 3.95,
                            PageCount = 256
                        }
                    );

                context.SaveChanges();
                
            }
        }
    }
}
